name: "test-eap-action"
description: "Validate the content of an .eap package for Axis ACAP"

inputs:
  app-path:
    description: "The path to the app to test"
    default: "*.eap"
  arch:
    description: "The expected architecture"
    default: ""
  token:
    description: "The FixedIT access token"
    required: true
  fappcli-version:
    description: "The version of fappcli to use"
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install fappcli
      uses: fixedit-ai/install-fappcli-action@main
      with:
        token: ${{ inputs.token }}
        fappcli-version: ${{ inputs.fappcli-version }}
    - name: Test application
      shell: bash
      run: |
        ARCH_ARG=`[[ -n "${{ inputs.arch }}" ]] && echo "--arch ${{ inputs.arch }}" || echo ""`
        fappcli-test -vv ${{ inputs.app-path }} $ARCH_ARG
